// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PestControll_CRM.Data;

#nullable disable

namespace PestControll_CRM.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PestControll_CRM.Data.Entity.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasColumnName("email");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PIB")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("pib");

                    b.Property<int?>("contactstatus_id")
                        .HasColumnType("int")
                        .HasColumnName("contactstatus_id");

                    b.HasKey("Id");

                    b.HasIndex("contactstatus_id");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("PestControll_CRM.Data.Entity.ContactStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("StatucColor")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("StatusColor");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("StatusName");

                    b.HasKey("Id");

                    b.ToTable("ContactStatus", (string)null);
                });

            modelBuilder.Entity("PestControll_CRM.Data.Entity.PhoneNumber", b =>
                {
                    b.Property<string>("phone_number")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("phone_number");

                    b.Property<int?>("contact_id")
                        .HasColumnType("int")
                        .HasColumnName("contact_id");

                    b.HasKey("phone_number");

                    b.HasIndex("contact_id");

                    b.ToTable("PhoneNumber", (string)null);
                });

            modelBuilder.Entity("PestControll_CRM.Data.Entity.Contact", b =>
                {
                    b.HasOne("PestControll_CRM.Data.Entity.ContactStatus", "Status")
                        .WithMany()
                        .HasForeignKey("contactstatus_id");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("PestControll_CRM.Data.Entity.PhoneNumber", b =>
                {
                    b.HasOne("PestControll_CRM.Data.Entity.Contact", "Contact")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("contact_id");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("PestControll_CRM.Data.Entity.Contact", b =>
                {
                    b.Navigation("PhoneNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
